  PRINT "...."  //This is for printing a string/
  PRINT 4       //This is prints a number, in this case, 4/
  var = 8       //stores 8 in var/
  name = "Bob"  //Stores the string Bob to the name variable/
  var = var + 2 //Adding 2 to var/
  PRINT var     //Outputs 10/

  WHILE var > 5 //While loop declaration/
    PRINT var
    PRINT "\n"  //Prints a newline/
    var = var - 1
  END           //Ends the while loop/

    IF var == 5
        PRINT "Equals to Five"
    ELSE
        PRINT "Var is not 5"
    END


    FOR x = 1 TO 5
        PRINT x
        PRINT "\n"
    END